"""empty message

Revision ID: 9ae04ab95148
Revises: ceee4af8fc98
Create Date: 2022-07-27 15:19:48.740210

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '9ae04ab95148'
down_revision = 'ceee4af8fc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # op.execute(text("INSERT INTO usuario (:id,:username,:password)"), 
    #             {"id":1, "username":"admin", "password":generate_password_hash("12345")}
    #             )
    
    op.add_column('contato', sa.Column('id_usuario', sa.Integer(), nullable=True))


    # op.execute(text("UPDATE contato SET id_usuario=1"))
    

    op.create_foreign_key(None, 'contato', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contato', type_='foreignkey')
    op.drop_column('contato', 'id_usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###
